name: Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g conventional-changelog-cli
      - run: conventional-changelog -p angular -i CHANGELOG.md -s
      - name: Commit changelog changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md [skip ci]"
      - name: Push changelog changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
